# ==== BASIC SITE INFO ====
title: "Kyle Brown — Aerospace Portfolio"
name: "Kyle Brown"
description: "UAV systems, propulsion, CAD design, and mission design. UCLA aerospace grad who builds the hardware and the code."

# Put a headshot in assets/profile/ then point to it:
profile_image: /assets/profile/profile.jpg

# Link to a PDF in /assets/pdf or an external link
resume-url: /assets/pdf/Kyle_Brown_Resume.pdf

# ==== CONTACT / EXTERNAL LINKS ====
external-links:
  linkedin: kyle-v-brown        # https://www.linkedin.com/in/kyle-v-brown
  github: kylebrown978          # https://github.com/kylebrown978
  # add others if you want:
  # stackoverflow: your-id
  # medium: your-handle

# ==== SKILLS (shown in nice categories) ====
skills:
  - category: CAD & Mechanical
    tools:
      - SolidWorks
      - DFMA
      - 3D Printing (FDM/SLA)
      - Composite layup

  - category: Flight & Controls
    tools:
      - PD/PID control
      - Waypoint planning
      - Sensor fusion (IMU/LiDAR)

  - category: Propulsion & Power
    tools:
      - Motor/ESC sizing & trades
      - Power distro / PDB
      - SEP vs chemical trade studies

  - category: Coding & Tools
    tools:
      - C++
      - MATLAB / Octave
      - Telemetry & data analysis

# ==== COLORS (navy + blue theme) ====
colors:
  text: "#0b0f1a"
  border: "#e1e6f0"
  link: "#1a73e8"
  highlight: "#0b3d91"
  background: "#ffffff"
  light_background: "#f3f6ff"

# ==== Contact form (optional—Formspree 8-char key) ====
# formspree-key: https://formspree.io/f/XXXXXXXX
